Repository PreOnBoarding-Team17/Week3_Table, pull requests merged in 2022-02, with the labels that each got.

#6 [정인권] feat: Modal 컴포넌트 구현
  src/App.tsx
  src/Components/SelectModal/index.tsx
  src/Utils/Constants/index.tsx
  src/Utils/Hooks/UsePrevious.tsx
  src/Utils/Hooks/UseToggle.tsx
  src/Utils/Interfaces/index.tsx
Labels: :joystick: 기능, 📱 UI

#7 [황상섭] feat: 네비게이션바, 모달 구현
  package.json
  public/index.html
  src/App.tsx
  src/Assets/Circle.png
  src/Components/Common/NavigationBar/InformationModal.tsx
  src/Components/Common/NavigationBar/index.tsx
  src/Utils/Constants/index.tsx
  src/Utils/Styles/GlobalStyles.ts
  src/react-app-env.d.ts
  yarn.lock
Labels: :joystick: 기능, 📱 UI

#8 [정인권] refactor: emtion css 적용
  src/App.tsx
  src/Components/SelectModal/index.tsx
  src/Utils/Hooks/UsePrevious.tsx
  src/Utils/Hooks/UseToggle.tsx
  src/Utils/Interfaces/index.tsx
Labels: :joystick: 기능, 📱 UI

#10 [현다솜] feat: Table 로직 추가 + 기본 템플릿 적용
  package.json
  src/App.tsx
  src/Components/Table/index.tsx
  yarn.lock
Labels: :joystick: 기능

#12 [현다솜] feat: Table 설정 적용 + 로직 추가
  src/Components/Table/index.tsx
  src/Utils/Constants/index.tsx
  src/Utils/Interfaces/index.tsx
Labels: :joystick: 기능, 📱 UI

#13 [황상섭] feat: Footer, SubmitButton 구현
  src/App.tsx
  src/Components/Common/NavigationBar/InformationModal.tsx
  src/Components/Common/SubmitButton/index.tsx
  src/Components/Footer/index.tsx
  src/Components/SelectModal/index.tsx
  src/Utils/Constants/index.tsx
  src/Utils/Interfaces/index.tsx
Labels: :joystick: 기능, 📱 UI

#15 [황상섭] feat: 테이블 셀에 Chip 구현
  package.json
  server/db.json
  src/Components/Common/SubmitButton/index.tsx
  src/Components/Footer/index.tsx
  src/Components/SettingCategory/index.tsx
  src/Components/Table/index.tsx
  src/Utils/Constants/index.tsx
  yarn.lock
Labels: :joystick: 기능, 📱 UI

#17 [현다솜] chore: table 사이즈 수정
  src/Components/SettingCategory/index.tsx
  src/Components/Table/index.tsx
  src/Utils/Styles/GlobalStyles.ts
Labels: 📱 UI

#18 [정인권] feature: 테이블 셀 클릭시 전체 데이터 모달창 구현하기
  src/Components/SettingCategory/index.tsx
  src/Components/Table/CellClickModal.tsx
  src/Components/Table/index.tsx
  src/Utils/Constants/Modal.tsx
  src/Utils/Interfaces/index.tsx
Labels: :joystick: 기능, 📱 UI
